<?php

/**
 * Implements hook_node_access().
 */
function msngr_compromisos_node_access($node, $op, $account) {
  if (!is_string($node) && in_array('user-institucional', $account->roles) && $op == 'update') {
    if($node->type == 'compromiso_de_gestion') {
      $user_entity = user_load($account->uid);
      return field_target_id($user_entity->field_institucion, 0) != field_target_id($node->field_institucion, 0) ? NODE_ACCESS_DENY : NODE_ACCESS_ALLOW;
    }
    /*if($node->type == 'meta') {
      $compromisos = get_compromiso_by_meta($node->nid);
      foreach ($compromisos as $compromiso) {
        $compromiso_node = node_load($compromiso->nid);
        $user_entity = user_load($account->uid);
        return field_target_id($user_entity->field_institucion, 0) != field_target_id($compromiso_node->field_institucion, 0) ? NODE_ACCESS_DENY : NODE_ACCESS_ALLOW;
      }
    }

    if($node->type == 'producto_meta' && isset($node->entity_view_prepared)) {
      return NODE_ACCESS_DENY;
    }*/
  }
}

/*
 * Implements hook_theme_registry_alter().
 */
/*function msngr_compromisos_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'auto_fill_id');
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  foreach ($template_file_objects as $key => $template_file) {
    if(!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}*/

/**
 * Implements hook_form_FORM_ID_alter().
 */
function msngr_compromisos_form_compromiso_de_gestion_node_form_alter(&$form, &$form_state, $form_id) {
  global $user;
//  dpm($form);

  $user_full = user_load($user->uid, TRUE);

  if (is_add_form($form_state) && in_array('usuario-institucional', $user->roles)) {
    auto_compromiso_form_title($user_full, $form, $form_state);
  }

  //Add css
  /*$form['#attached'] = array(
    'css' => array('sites/all/modules/custom/auto_fill_id/css/compromiso_form.css'),
  );*/

  //Compromiso de Gestión title disabled
  $form['title']['#disabled'] = TRUE;

  //Restrict access
  $form['field_porcentaje_de_avance_compr']['#access'] = FALSE;
  $form['field_year_compromiso']['#access'] = FALSE;
  $form['field_estado']['#access'] = FALSE;
  $form['field_id_compromiso']['#access']= FALSE;

  //Items de compromiso
  //$form['field_item_compromiso'][LANGUAGE_NONE]['#title'] = 'Items de Compromiso';
  //$form['field_item_compromiso'][LANGUAGE_NONE]['add_more']['#value'] = 'Añadir Nuevo Item de Compromiso';
}

function is_add_form($form_state){
  return !isset($form_state['node']->nid);
}

function auto_compromiso_form_title($user, &$form, &$form_state) {
  $ins_nid = field_target_id($user->field_institucion, 0);

  $ins = node_load($ins_nid);
  $form['field_institucion']['#disabled'] = TRUE;
  $form['field_institucion'][LANGUAGE_NONE][0]['target_id']['#default_value'] = t('@institution (@nid)', array('@institution' => $ins->title, '@nid' => $ins_nid));
  $form_state['values']['field_institucion'][LANGUAGE_NONE][0]['target_id'] = $ins_nid;
  $form['title']['#default_value'] = date('Y').'-'.$ins->title;
}
