<?php
/**
 * @file
 * Archivo para prueba de modulo
 */

/**
 * Implementa hook_menu().
 */
function pruebam_menu() {
  $items = array();
  $items['sngr/autoevaluacion'] = array(
    'title' => t('Formulario'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('form_autoevaluacion'),
    'access arguments' => array('access content'),
    'description' => t('Formulario'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Returns the render array for the form.
 */
function form_autoevaluacion($form, &$form_state) {
/*
*Rectangulo para división
*/
  $form['Página'] = array(
    '#type' => 'fieldset',
    '#title' => t('Página'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['Página']['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Título'),
    '#required' => TRUE,
    '#default_value' => "Título",
    '#description' => "Por favor agregue el Título",
    '#size' => 20,
    '#maxlength' => 20,
  );
  
  $form['Página']['body'] = array(
    '#type' => 'textfield',
    '#title' => t('Cuerpo'),
    '#required' => TRUE,
  );
 
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  
 watchdog('title', $form['Página']['body']);

  return $form;
}



/**
 * Add a submit handler/function to the form.
 *
 * This will add a completion message to the screen when the
 * form successfully processes
 */
function form_autoevaluacion_submit($form, &$form_state) {
	drupal_set_message(t('El Formulario se envio correctamente.'));
}
?>
