<?php

/**
 * @file
 * Code for the Planes generales de Emergencia feature.
 */

include_once 'monitorsngr_pge.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function monitorsngr_pge_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner === 'ctools' && $plugin_type === 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_form_alter().
 */
function monitorsngr_pge_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id === 'pge_formulario_insumos_node_form') {
    $form['#attached']['js'][] = drupal_get_path('module', 'monitorsngr_pge') . '/js/pge_supplies_form.js';
    $query = drupal_get_query_parameters();
    if (count($query) && !empty($query['decree'])) {
      $decree_id = check_plain($query['decree']);
      if (is_numeric($decree_id)) {
        $decree_wrapper = entity_metadata_wrapper('node', $decree_id);
        $form['field_decreto_emergencia'][LANGUAGE_NONE][0]['target_id']['#default_value'] = '"' . $decree_wrapper->label() . ' (' . $decree_wrapper->getIdentifier() . ')"';
      }
    }
  }
  if ($form_id === 'peg_ficha_tecnica_compromiso_node_form') {
    $query = drupal_get_query_parameters();
    if (count($query) && !empty($query['decree'])) {
      $decree_id = check_plain($query['decree']);
      if (is_numeric($decree_id)) {
        global $user;
        $user_wrapper = entity_metadata_wrapper('user', $user);
        $wrapper = entity_metadata_wrapper('node', $decree_id);
        $consecutive = monitorsngr_pge_get_compromise_consecutive($decree_id) + 1;
        $decree_year = date('Y', $wrapper->field_fecha->value());
        $institution_name = $user_wrapper->field_institucion->label();
        $form['title']['#default_value'] = $consecutive . '-' . $decree_year . ' ' . $institution_name;
        $form['field_decreto_emergencia'][LANGUAGE_NONE][0]['target_id']['#default_value'] = '"' . $wrapper->label() . ' (' . $wrapper->getIdentifier() . ')"';
        $form['#after_build'][] = 'peg_ficha_tecnica_compromiso_node_form_after_build';
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function monitorsngr_pge_theme($existing, $type, $theme, $path) {
return array(
  'monitorsngr_pge_supplie_form_author_info' => array(
    'variables' => array(
      'bottom_text' => array(),
      'download_link' => array(),
    ),
    'template' => 'monitorsngr-pge-supplie-form-author-info',
    'path' => drupal_get_path('module', 'monitorsngr_pge') . '/templates',
  ),
);

/**
 * After build function for peg_ficha_tecnica_compromiso_node_form form.
 */
function peg_ficha_tecnica_compromiso_node_form_after_build($form, &$form_state) {
  $form['title']['#attributes']['readonly'] = 'readonly';
  $form['field_decreto_emergencia'][LANGUAGE_NONE][0]['target_id']['#attributes']['readonly'] = 'readonly';
  return $form;
}

/**
 * Helper function to get the consecutive number of the PGE compromises.
 */
function monitorsngr_pge_get_compromise_consecutive($emergency_decree_id) {
  $query = db_select('field_data_field_decreto_emergencia', 'f')
    ->fields('f', array('field_decreto_emergencia_target_id'))
    ->condition('field_decreto_emergencia_target_id', $emergency_decree_id)
    ->condition('entity_type', 'node')
    ->condition('bundle', 'peg_ficha_tecnica_compromiso')
    ->execute();
  return $query->rowCount();
}
