<?php

/**
 * @file
 * Code for the Planes generales de Emergencia feature.
 */

include_once 'monitorsngr_pge.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function monitorsngr_pge_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner === 'ctools' && $plugin_type === 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_form_alter().
 */
function monitorsngr_pge_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id === 'pge_formulario_insumos_node_form') {
    $form['#attached']['js'][] = drupal_get_path('module', 'monitorsngr_pge') . '/js/pge_supplies_form.js';
  }
}

/**
 * Implements hook_theme().
 */
function monitorsngr_pge_theme($existing, $type, $theme, $path) {
  return array(
    'monitorsngr_pge_supplie_form_author_info' => array(
      'variables' => array(
        'bottom_text' => array(),
        'download_link' => array(),
      ),
      'template' => 'monitorsngr-pge-supplie-form-author-info',
      'path' => drupal_get_path('module', 'monitorsngr_pge') . '/templates',
    ),
  );
}
